const GLOBAL_KNOWLEDGE_BASE = [
    { term: "Apple", weight: 95 },
    { term: "Amazon", weight: 90 },
    { term: "AI Ethics", weight: 80 },
    { term: "Augmented Reality", weight: 75 },
    { term: "Automation Tools", weight: 70 },
    { term: "Algorithms", weight: 65 },
    { term: "Azure Cloud", weight: 60 },
    { term: "Android 15", weight: 55 },
    
    { term: "Blockchain", weight: 95 },
    { term: "Big Data", weight: 90 },
    { term: "Beta Testing", weight: 85 },
    { term: "Business Intelligence", weight: 80 },
    { term: "Budgeting Software", weight: 75 },
    { term: "Biometrics", weight: 70 },
    { term: "ByteDance", weight: 65 },

    { term: "Cybersecurity", weight: 95 },
    { term: "Cloud Computing", weight: 90 },
    { term: "CRM Systems", weight: 85 },
    { term: "Customer Experience", weight: 80 },
    { term: "Cryptocurrency", weight: 75 },
    { term: "Code Review", weight: 70 },
    
    { term: "Data Migration", weight: 95 },
    { term: "Decentralization", weight: 90 },
    { term: "Digital Marketing", weight: 85 },
    { term: "Database Management", weight: 80 },
    { term: "DevOps Practices", weight: 75 },
    { term: "Disaster Recovery", weight: 70 },

    { term: "E-commerce Trends", weight: 95 },
    { term: "Edge Computing", weight: 90 },
    { term: "Enterprise Software", weight: 85 },
    { term: "Encryption Standards", weight: 80 },
    { term: "Employee Training", weight: 75 },

    { term: "Fintech Innovation", weight: 95 },
    { term: "Future of Work", weight: 90 },
    { term: "Figma Tutorials", weight: 85 },
    { term: "Frontend Development", weight: 80 },
    { term: "Financial Modeling", weight: 75 },
    
    { term: "Google", weight: 95 },
    { term: "GenAI", weight: 90 },
    { term: "GitHub Actions", weight: 85 },
    { term: "Green Technology", weight: 80 },
    { term: "Global Supply Chain", weight: 75 },

    { term: "Hardware Security", weight: 95 },
    { term: "Hybrid Cloud", weight: 90 },
    { term: "Human Resources Tech", weight: 85 },
    { term: "Hiring Strategies", weight: 80 },
    { term: "Health Monitoring", weight: 75 },

    { term: "Intel", weight: 95 },
    { term: "IoT Devices", weight: 90 },
    { term: "Information Security", weight: 85 },
    { term: "Investment Analysis", weight: 80 },
    { term: "IT Infrastructure", weight: 75 },
    { term: "Innovation Labs", weight: 70 },
    
    { term: "Jira Workflow", weight: 95 },
    { term: "JavaScript Frameworks", weight: 90 },
    { term: "Job Market Trends", weight: 85 },
    { term: "Jupyter Notebook", weight: 80 },
    { term: "Java Programming", weight: 75 },
    
    { term: "Kubernetes", weight: 95 },
    { term: "Key Performance Indicators", weight: 90 },
    { term: "Knowledge Management", weight: 85 },
    { term: "Kotlin Development", weight: 80 },
    { term: "KPMG Services", weight: 75 },

    { term: "Legacy Systems", weight: 95 },
    { term: "Linux Security", weight: 90 },
    { term: "Lead Generation", weight: 85 },
    { term: "Legal Compliance", weight: 80 },
    { term: "Learning Management System", weight: 75 },
    
    { term: "Microsoft", weight: 95 },
    { term: "Machine Learning", weight: 90 },
    { term: "Metaverse", weight: 85 },
    { term: "Mobile Development", weight: 80 },
    { term: "Market Segmentation", weight: 75 },
    { term: "Mergers & Acquisitions", weight: 70 },

    { term: "Networking Protocols", weight: 95 },
    { term: "Natural Language Processing", weight: 90 },
    { term: "NFT Marketplace", weight: 85 },
    { term: "No-Code Platforms", weight: 80 },
    { term: "Next.js Framework", weight: 75 },
    { term: "Nvidia GPU", weight: 70 },

    { term: "Open Source", weight: 95 },
    { term: "Operating Systems", weight: 90 },
    { term: "Organizational Structure", weight: 85 },
    { term: "OKR Methodology", weight: 80 },
    { term: "Online Privacy", weight: 75 },
    
    { term: "Product Management", weight: 95 },
    { term: "Project Roadmap", weight: 90 },
    { term: "Python Programming", weight: 85 },
    { term: "Process Optimization", weight: 80 },
    { term: "Public Relations", weight: 75 },
    { term: "Payment Gateways", weight: 70 },

    { term: "Quality Assurance", weight: 95 },
    { term: "Quantum Computing", weight: 90 },
    { term: "Quarterly Review", weight: 85 },
    { term: "Query Optimization", weight: 80 },
    { term: "Qualcomm Chips", weight: 75 },
    
    { term: "Risk Assessment", weight: 95 },
    { term: "Remote Work Policy", weight: 90 },
    { term: "Robotics", weight: 85 },
    { term: "Recruitment Strategy", weight: 80 },
    { term: "React Development", weight: 75 },
    
    { term: "Software Architecture", weight: 95 },
    { term: "Supply Chain Management", weight: 90 },
    { term: "Salesforce", weight: 85 },
    { term: "Serverless Computing", weight: 80 },
    { term: "Startup Funding", weight: 75 },
    { term: "Security Audit", weight: 70 },

    { term: "Telecommuting", weight: 95 },
    { term: "Technical Documentation", weight: 90 },
    { term: "Target Audience", weight: 85 },
    { term: "Time Management", weight: 80 },
    { term: "Tokenization", weight: 75 },
    
    { term: "User Experience", weight: 95 },
    { term: "UI/UX Design", weight: 90 },
    { term: "Unity 3D", weight: 85 },
    { term: "Upgrade Path", weight: 80 },
    { term: "Utility Computing", weight: 75 },

    { term: "Virtual Reality", weight: 95 },
    { term: "Venture Capital", weight: 90 },
    { term: "Version Control", weight: 85 },
    { term: "Video Conferencing", weight: 80 },
    { term: "Vulnerability Scanning", weight: 75 },
    { term: "VMware Solutions", weight: 70 },

    { term: "Web Development", weight: 95 },
    { term: "Workforce Planning", weight: 90 },
    { term: "Wireless Technology", weight: 85 },
    { term: "Website Analytics", weight: 80 },
    { term: "White Label Software", weight: 75 },
    
    { term: "X-ray Vision Tech", weight: 95 },
    { term: "XaaS (Everything as a Service)", weight: 90 },
    { term: "XML Schema", weight: 85 },
    { term: "Xperia Devices", weight: 80 },
    { term: "Xen Virtualization", weight: 75 },
    
    { term: "Y Combinator", weight: 95 },
    { term: "Yahoo Mail", weight: 90 },
    { term: "Yearly Goals", weight: 85 },
    { term: "Yield Management", weight: 80 },
    { term: "YouTube Marketing", weight: 75 },

    { term: "Zero Trust Architecture", weight: 95 },
    { term: "Zuckerberg", weight: 90 },
    { term: "Zoom Meetings", weight: 85 },
    { term: "Zenith Technology", weight: 80 },
    { term: "Zip Code Data", weight: 75 },

    { term: "人工智慧", weight: 95 },
    { term: "物聯網應用", weight: 90 },
    { term: "大數據分析", weight: 85 },
    { term: "安卓系統", weight: 80 },
    { term: "雲端服務", weight: 75 },
    { term: "產品設計", weight: 70 },
    
    { term: "區塊鏈技術", weight: 95 },
    { term: "半導體產業", weight: 90 },
    { term: "邊緣運算", weight: 85 },
    { term: "報表系統", weight: 80 },
    { term: "筆記本電腦", weight: 75 },
    
    { term: "創新策略", weight: 95 },
    { term: "市場趨勢", weight: 90 },
    { term: "創意發想", weight: 85 },
    { term: "商業模式", weight: 80 },
    { term: "財務報表", weight: 75 },
    { term: "資料庫結構", weight: 70 },

    { term: "數位轉型", weight: 95 },
    { term: "分散式系統", weight: 90 },
    { term: "電商平台", weight: 85 },
    { term: "導航技術", weight: 80 },
    { term: "電競設備", weight: 75 },
    
    { term: "雲端儲存", weight: 95 },
    { term: "電子商務", weight: 90 },
    { term: "客戶關係管理", weight: 85 },
    { term: "電子支付", weight: 80 },
    { term: "遠距工作", weight: 75 },
    
    { term: "服務流程", weight: 95 },
    { term: "風險控管", weight: 90 },
    { term: "金融科技", weight: 85 },
    { term: "防火牆設置", weight: 80 },
    { term: "法規遵循", weight: 75 },
    
    { term: "公司治理", weight: 95 },
    { term: "供應鏈優化", weight: 90 },
    { term: "高階主管", weight: 85 },
    { term: "國際貿易", weight: 80 },
    { term: "光纖網路", weight: 75 },
    { term: "個人隱私", weight: 70 },
    
    { term: "環境保護", weight: 95 },
    { term: "人力資源", weight: 90 },
    { term: "混合現實", weight: 85 },
    { term: "合約審查", weight: 80 },
    { term: "客戶服務", weight: 75 },
    
    { term: "資訊安全", weight: 95 },
    { term: "產業分析", weight: 90 },
    { term: "內部稽核", weight: 85 },
    { term: "投資組合", weight: 80 },
    { term: "智慧城市", weight: 75 },

    { term: "技術架構", weight: 95 },
    { term: "績效考核", weight: 90 },
    { term: "金融法規", weight: 85 },
    { term: "教育訓練", weight: 80 },
    { term: "進度管理", weight: 75 },
    
    { term: "開發流程", weight: 95 },
    { term: "客戶開發", weight: 90 },
    { term: "科技趨勢", weight: 85 },
    { term: "關鍵指標", weight: 80 },
    { term: "跨部門協作", weight: 75 },
    
    { term: "領導力發展", weight: 95 },
    { term: "流程自動化", weight: 90 },
    { term: "零售科技", weight: 85 },
    { term: "離職率分析", weight: 80 },
    { term: "藍牙技術", weight: 75 },
    
    { term: "媒體公關", weight: 95 },
    { term: "目標設定", weight: 90 },
    { term: "敏捷開發", weight: 85 },
    { term: "模型訓練", weight: 80 },
    { term: "密碼學原理", weight: 75 },

    { term: "網路安全", weight: 95 },
    { term: "軟體工程", weight: 90 },
    { term: "自然語言處理", weight: 85 },
    { term: "能源管理", weight: 80 },
    { term: "內容行銷", weight: 75 },
    { term: "新創公司", weight: 70 },

    { term: "作業系統", weight: 95 },
    { term: "組織文化", weight: 90 },
    { term: "外部顧問", weight: 85 },
    { term: "開放平台", weight: 80 },
    { term: "會議記錄", weight: 75 },
    
    { term: "專案管理", weight: 95 },
    { term: "品牌建立", weight: 90 },
    { term: "平板電腦", weight: 85 },
    { term: "程式語言", weight: 80 },
    { term: "品質保證", weight: 75 },
    { term: "生產效率", weight: 70 },

    { term: "量化交易", weight: 95 },
    { term: "區間分析", weight: 90 },
    { term: "潛在客戶", weight: 85 },
    { term: "趨勢預測", weight: 80 },
    { term: "全球佈局", weight: 75 },

    { term: "軟體定義網路", weight: 95 },
    { term: "人力招募", weight: 90 },
    { term: "遠端監控", weight: 85 },
    { term: "資料恢復", weight: 80 },
    { term: "日常開支", weight: 75 },
    
    { term: "策略規劃", weight: 95 },
    { term: "資料科學", weight: 90 },
    { term: "數據加密", weight: 85 },
    { term: "聲學技術", weight: 80 },
    { term: "社交媒體", weight: 75 },
    { term: "市場調查", weight: 70 },

    { term: "產品測試", weight: 95 },
    { term: "團隊合作", weight: 90 },
    { term: "通訊協定", weight: 85 },
    { term: "圖形處理器", weight: 80 },
    { term: "統計方法", weight: 75 },
    
    { term: "使用者經驗", weight: 95 },
    { term: "網頁開發", weight: 90 },
    { term: "雲端運算", weight: 85 },
    { term: "營運成本", weight: 80 },
    { term: "用戶介面", weight: 75 },
    
    { term: "虛擬化技術", weight: 95 },
    { term: "投資者關係", weight: 90 },
    { term: "供應商管理", weight: 85 },
    { term: "影片編輯", weight: 80 },
    { term: "風險評估", weight: 75 },

    { term: "物聯網安全", weight: 95 },
    { term: "網站分析", weight: 90 },
    { term: "無線充電", weight: 85 },
    { term: "危機處理", weight: 80 },
    { term: "文化建設", weight: 75 },
    { term: "未來趨勢", weight: 70 },
    
    { term: "新產品發表", weight: 95 },
    { term: "行動支付", weight: 90 },
    { term: "銷售報告", weight: 85 },
    { term: "系統整合", weight: 80 },
    { term: "學習曲線", weight: 75 },
    
    { term: "研究開發", weight: 95 },
    { term: "業務拓展", weight: 90 },
    { term: "預算編列", weight: 85 },
    { term: "運營效率", weight: 80 },
    { term: "預測模型", weight: 75 },

    { term: "自動化測試", weight: 95 },
    { term: "資源配置", weight: 90 },
    { term: "智慧型手機", weight: 85 },
    { term: "自駕技術", weight: 80 },
    { term: "組織變革", weight: 75 }
];

const INITIAL_KEYWORDS = [
    "探索 NovaSeek", 
    "來看看", 
];